# This is a basic workflow to help you get started with Actions

name: gif comment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "comment"
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a single command using the runners shell
      - name: Add a funny comment
        uses: Marta83/funny-comment-action@v2.1
        id: funnyComment
        with: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
            comment_type: 'gif'
